/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/914826cb-fff4-42c1-b3b6-03656e568d3b 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int potvalue;
  bool led1;
  bool led2;
  bool led3;
  bool led4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
int device1=D2;
int device2=D3;
int device3=D4;
int device4=D5;
int pot=A0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(device1,OUTPUT);
  pinMode(device2,OUTPUT);
  pinMode(device3,OUTPUT);
  pinMode(device4,OUTPUT);
  pinMode(pot,INPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  potvalue=analogRead(pot);
}



/*
  Since Led1 is READ_WRITE variable, onLed1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed1Change()  {
  // Add your code here to act upon Led1 change
if(led1)
{
 digitalWrite(device1,HIGH); 
}
else{
  digitalWrite(device1,LOW);
}
}

/*
  Since Led2 is READ_WRITE variable, onLed2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed2Change()  {
  // Add your code here to act upon Led2 change
  if(led2)
{
 digitalWrite(device2,HIGH); 
}
else{
  digitalWrite(device2,LOW);
}
}

/*
  Since Led3 is READ_WRITE variable, onLed3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed3Change()  {
  // Add your code here to act upon Led3 change
  if(led3)
{
 digitalWrite(device3,HIGH); 
}
else{
  digitalWrite(device3,LOW);
}
}

/*
  Since Led4 is READ_WRITE variable, onLed4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed4Change()  {
  // Add your code here to act upon Led4 change
  if(led4)
{
 digitalWrite(device4,HIGH); 
}
else{
  digitalWrite(device4,LOW);
}
}
